### ISSUE TITLE
Principal and password management for SCRAM/PLAINTEXT

### ISSUE THREAD

**Issue by denisko890** [streamthoughts/jikkou#391]
**Is your feature request related to a problem? Please describe.**
The main challenge with automation is the need to manage users. I would like to have functionality to set a password for users.

**Describe the solution you'd like**
An endpoint that will set the password for the user, according to the specified security mechanism. SCRAM/PLAINTEXT

**Describe alternatives you've considered**
Kafkacat or regular bash console. If there are options to manage users and passwords using REST API, I will be glad to get feedback.

**Comment by fhussonnois** [comment]
Hi @denisko890, thank you for your feature request. If I understand it correctly you would like to manage SCRAM users through YAML descriptor files so that Jikkou can reconcile them with your Apache Kafka cluster ? I think the main challenges is for storing passwords. As far as I know, only Kraft provides the client for passing a SHA512/256 hashed password with a salt. Using Kafka/Zookeeper passwords are passed in plaintext using the Kafka API client.

**Comment by denisko890** [comment]
Hi @fhussonnois! Thanks for the reply!
Yes, you understood correctly, I would like to manage users and passwords using YAML.
For example Terraform-Kafka-Provider allows to create/change password for users, but it does not allow to import current ones. I don't think it will be possible to import either. But managing users with Jikkou would be nice.
