### ISSUE TITLE
connecting to on-prem schema registry with self-signed certificate

### ISSUE THREAD

**Issue by CurryWurry** [streamthoughts/jikkou#425]
We are running an on-prem Confluent schema registry, but when trying to get subjects we get: "Error: CompletionException: io.streamthoughts.jikkou.http.client.RestClientException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

configuring ssl and connecting to the kafka brokers works without any issues. Adding the schema registry's self signed certificate to the JDK's truststore did not work. Are ssl properties evaluated in the jikkou.schemaRegistry namespace? Looking at the documentation we can only specify url, vendor, authMethod and basic auth properties.

**Comment by fhussonnois** [comment]
Hi @CurryWurry, I think that for the SSL Authentication is not support by Jikkou. Are you using a Schema Registry configured with `ssl.client.auth=true` (confluent doc: https://docs.confluent.io/platform/current/schema-registry/security/index.html#additional-configurations-for-https). I will push a PR so that you will be able to configure the ssl properties for the schema registry.

**Comment by CurryWurry** [comment]
Hi @fhussonnois , yes, we have configured schemaRegistry exactly like we did for the kafka client, but these properties are indeed ignored for both schemaRegistry and kafkaConnect. We managed to temporarily work around this limitation by providing JVM parameters to the Jikkou cli: `jikkou -Djavax.net.ssl.keyStore=./pre-prod/keystore.p12 ... get sr`
